version: '1'
services:
  db:
    image: docker.io/mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "4306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    command: [--ignore-db-dir=lost+found]
  phpmyadmin:
    image: docker.io/phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  wordpress:
    depends_on:
      - db
    image: docker.io/wordpress:6.0.1
    volumes:
      - ./src/themes:/var/www/html/wp-content/themes
      - ./src/plugins:/var/www/html/wp-content/plugins
      - ./src/uploads:/var/www/html/wp-content/uploads
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress